changelog:
  categories:
    - title: ⭐ New Features
      labels:
        - "*"
    - title: ⚠️ Breaking Changes
      labels:
        - major-update
        - breaking-change
    - title: 🐞 Bug Fixes
      labels:
        - bugfix
    - title: 🔨 Dependency Upgrades
      labels:
        - dependencies
    - title: 📔 Documentation
      labels:
        - documentation
