= Syntax Guide
:source-language: rql
:page-partial:
//Keep :page-partial: attribute so that users of Antora versions lower than 2.2 will also be able to include the page without running into ordering problems. More details: https://docs.antora.org/antora/latest/page/page-partial/  


Learn how to compose queries that are based on and conform to Bosch Semantic Stack RQL.

== Main operators

With Bosch Semantic Stack RQL, a query can use up to three operators: 

* `select`
* `filter`
* `option`
//TODO ? Is it option or options? Found it both in singular and plural, went for singular.

The following example represents the general form of a Bosch Semantic Stack RQL query string.

----
select=id,name&filter=ge(id,4711)&option=sort(+name,-description),limit(10,5)
----

The above query string means:

select:: Select the attributes `id` and `name`.

filter:: Filter for `id` attribute values that are _greater than or equal to_ `4711`.

options:: *Sort* the results _ascending_ by `name` and _descending_ by `description`. -- Note that the attributes used for sorting (e.g., `description`) do not have to appear in the select operator. +
*Limit* the returned results to 5 results, starting at result no. 10. -- Note that the start of indices depends entirely on the implementation.
// TODO ? Implementation of what? (New sentence: "Note that the start of indices depends entirely on how you implement ... (what?).")
// TODO ? Does it matter whether "sort" or "limit" comes first? (Note that here in this example it is first sort then limit. Further below (in the "options" section), another example swaps this order. Does the order matter? Do we recommend any order? Like: first sort the data and then take results xyz?)


== Select

The `select` operator trims an API response down to only a given set of attributes. That means, the data of any further attributes will not be included in the API response.

The general form of the `select` operator string looks as follows:

----
select=attribute1,attribute2,attributeN
----

User-defined select can be requested via RQL for a root entity.
The attributes names are separated by a comma.
All child entities will then not be loaded.
This means that response times can be significantly improved if only the requested information is returned.

Example: Load (Select) only IDs and name (select) and do that only for the root entity.

----
select=id,name
----

== Filter

The `filter` operator trims an API response down to match only a given set of filter criteria. That means, data not matched by the filter criteria will not be included in the API response.

The general form of the `filter` operator string looks as follows:

----
filter={filter expression}
----

The value is an expression that uses one of the following operators:

* Comparison: `+++<abbr title="equals">eq</abbr>+++`,
`+++<abbr title="value is one of a given list">in</abbr>+++`,
`+++<abbr title="not equals">ne</abbr>+++`,
`+++<abbr title="greater than">gt</abbr>+++`,
`+++<abbr title="greater or equal than">ge</abbr>+++`,
`+++<abbr title="less than">lt</abbr>+++`,
`+++<abbr title="less or equal than">le</abbr>+++`,
`like` and `likeIgnoreCase`;
* Logical: `and`, `or` and `not`.

The following list illustrates some example filter expressions:
likeIgnoreCase(description,"*my device*"): All digital twins that have a description containing "my device"in(twinCategory,"Machine","Device"): All digital twins that have a twinCategory of either "Machine" or "Device"and(eq(twinCategory,"Printer"), eq(labels.name,"Floor1")):
All digital twins with given twinCategory and at least one label with name Floor1

Here is a definition of the common operators (individual stores may have support for more less operators):

=== Comparison operators

The following comparison operators are supported.
// TODO (old) The excerpts of the language definition below shows the main operators and their restrictions. 


.Comparison operators

[options="header"]
|===
| Operator Expression               | Description
| eq(<attribute>,<value>)           | Filters objects where the value of the specified attribute equals the provided value.
| ge(<attribute>,<value>)           | Filters for objects where the value of the specified attribute is greater than or equal to the provided value.
| gt(<attribute>,<value>)           | Filters for objects where the value of the specified attribute is greater than the provided value.
| in(<attribute>,<array-of-values>) | Filters for objects where the value of the specified attribute is present in the provided array.
| le(<attribute>,<value>)           | Filters for objects where the value of the specified attribute is less than or equal to the provided value.
| lt(<attribute>,<value>)           | Filters for objects where the value of the specified attribute is less than the provided value.
| ne(<attribute>,<value>)           | Filters for objects where the value of the specified attribute is not equal to the provided value.
| count()                           | The count of records in the result set of the query is not yet implemented.
|===

=== Logical operators

The following logical operators are supported.

.Logical Operator

[options="header"]
|===
| Logical Expression                | Description
| and(<operator1>,<operator2>,...)  | Executes all the provided queries.
| or(<operator1>,<operator2>,...)   | The combination of the provided queries.
| not(<operator1>,<operator2>,...)  | Negates the provided query.
|===

== Option

The `option` operator sorts and limits API responses. That means, you can prevent an arbitrary order of your retrieved results. With this user-defined sorting, clients are responsible for requesting data in the order that fits their needs. 

The general form of the `option` operator string looks as follows:

----
option=limit(),sort()
----
//TODO ? Does the order of the limit and sort components matter? Found it in both variants on this page. 

As an example, the `option` string could look like this:

----
option=limit(10,5),sort(-attribute1,+attribute2)
----

With user-defined sorting, the client is responsible for preventing an arbitrary order of the retrieved results.
// TODO Put this sentence elsewhere

=== Sorting

To sort the retrieved data, use the `sort` operator as part of the `option` operator.

----
option=sort([+-]attributeN)
----

The `sort` operator sorts the data based on the specified attributes:

* It starts sorting with the first attribute, then proceeds to the next etc. 
* To separate the attribute names that you require for sorting, use a comma.
* For each attribute, you can specify whether to sort the results in ascending or descending order, indicating sort order by the *+* or *-* prefix.
** For ascending sort order, use the *+* prefix.
** For descending sort order, use the *-* prefix. 

Example:
----
option=sort(-attribute1,+attribute2,[+-]attributeN)
----
In the example above, results will first be sorted in descending order for `attribute1`, then will further be sorted in ascending order for `attribute2`, and then ascending or descending for any more attributes that might be added.

=== Pagination

To control the pagination of the retrieved data, use the `limit` operator as part of the `option` operator.

----
option=limit(start,count)
----

The syntax is related to *offset pagination*. That means the `start` and `count` parts in the string above conceptually stand for the following numbers:

* `start` specifies where to start fetching data, also known as _offset_
* `count` indicates how many results to fetch per page

Example:
----
option=limit(10,5)
----
In the example above, results will start at result no. 10 and 5 results will be included in the API response.

Currently, only offset pagination is provided with Bosch Semantic Stack RQL. We may add cursor-based pagination in the future.

== Attribute names

Attribute names used in `select`, `filter`, and `sort` statements are restricted to the following syntax: +
`[a-zA-Z_][a-zA-Z0-9/_]*`
//TODO ? Isn't this rather indicating the allowed characters whereas the syntax comes in the examples below?

*Examples:*

name:: simple attribute named 'name'

id:: simple attribute named 'id'

location_v_2:: simple attribute name containing underscore and numbers

_someStrangeThing:: attribute names _may_ start with underscore but why would you?
//TODO ? Why not?

address/street:: _nested_ attribute 'street' of parent attribute 'address'

99NotValid:: *invalid* -- attributes must not start with numbers

/alsoNotValid:: *invalid* -- attributes may not start with nesting separator

willBeParsedButHasNoMeaning/:: *no meaning* -- the parser will read this but it makes no sense and *may be removed in future releases*
//TODO ? Why doesn't it make sense? Because it is indicating a parent without adding the child?

Attributes can be nested by separating them using `.`.
//TODO ? In addition to being nested with / as indicated for "address/street"?

*Example:* `address.street`

=== Data types

==== Integer numbers

Integer numbers will be parsed in the smallest Java data type they fit (Integer, Long, BigInteger).

*Example:* `ge(foo,42)`

==== Real numbers

Real numbers will always be parsed into the Java data type `BigDecimal`.

*Example:* `lt(foo,7.23246)`

==== null

Will get mapped to null.

*Example:* `eq(foo,null)`

==== Strings

Can be any Unicode (except Unicode escapes `\u1234`) with the escaping rules closely following Java:

Escape-char is backslash `\`, possible escape sequences are:

`\\`:: Backslash itself
`\t`:: Tabulator
`\n`:: Newline
`\r`:: Carriage return
`\"`:: Double Quote
`\f`:: Formfeed - *DO NOT USE* _this might be removed in future_
`\b`:: Backspace - *DO NOT USE* _this might be removed in future_
//TODO ? What do they do, why would I add them to a query?

==== Times

This parser (and model) support time literals as `OffsetDateTime` represented in a *subset* of _ISO 8601_.
Some less used features of ISO 8601 are not supported -- and most likely will not in near future:

* Reduced Precision: giving a partial time `hh` or `hh:mm` is not supported.
* Fractional hours and minutes (_ISO8601_ states that you can use fractions of the most precise time component (hour, minute, second).
As we only support a fixed precision including seconds this is not supported.

So `2007-12-03T10:15Z` and `2007-12-03T10:15+4:27` are valid _ISO8601_ but *not* valid RQL.
//TODO ? Like generally not valid for RQL or not valid within this Bosch Semantic Stack RQL project? (Also, just noting that so far it was not explained how to actually set up the RQL project so that it can be used. Or is there nothing to set up because the DTR supports it just natively? (Then why is it an extra open-source project and not just a DTR feature? Can it also be used for other registries or even any other API?))

Valid examples are `2007-12-03T10:15:30.0123Z` and `2007-12-03t10:15:30+04:37`.

<<<
//TODO ?

=== Set comparisons
//TODO ? Means comparing data SETs? Or to set a comparison? Or that there are some comparisons that have been set by default? Lost here. What about an intro sentence and one or two examples like above?

The `in` statement does not support `null` as a literal and only _pure_ lists, i.e., only floats, only strings, or only integers.

Wildcards for the like operators are `?` for a single undefined character and `*` for any number of characters.

=== Simple comparisons
//TODO ? How do simple comparisons differ from "set comparisons"?

<1> Supports all literals
<2> Does not support booleans or null, as less/greater are not defined independent of implementation
<3> Supports only strings
//TODO ? Why formatting the numbers as if they described something like a legend for a chart or map? Is this just a bulleted list? What does it even mean, this list? An intro sentence would help.
